name: Build Package

on:
  push:
    branches: [ master ]
    tags: "*"
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build native extension
      run: |
        sudo apt-get install -y build-essential cppad coinor-libipopt-dev
        python setup.py develop
    - name: Lint with flake8
      run: |
        pip install flake8
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 cppyad --count --exit-zero --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pytest